### ISSUE TITLE
Picking between ts-mockito forks

### ISSUE THREAD

**Issue by mebble** [johanblumenberg/ts-mockito#10]
Hi, I'm looking for a ts-mockito fork that will be maintained long-term. Someone mentioned your fork on this thread:
https://github.com/NagRock/ts-mockito/issues/212

The thread concluded with creating a new community-maintained fork:
https://github.com/TypeStrong/ts-mockito

Do you plan to keep maintaining this or would you merge with the TypeStrong repo? Asking because both repos are actively being maintained and it would be clearer to have one repo for this project, preferably maintained by a community instead of an individual.

Also as an aside: so far the original project and the TypeStrong fork are at v2 whereas this fork is currently at v1. Do you plan to update this to keep up with v2?

**Comment by johanblumenberg** [comment]
Hi @mebble 

The plan is to add all features of this repository to the TypeStrong repository.
Until I find time to do so, I will maintain this repository.

**Comment by mebble** [comment]
Thanks, @johanblumenberg
